# Imports Always Frist

In [7]:
import requests
import pandas as pd
import json

# Extracting Data from Wold Bank

In [20]:
# Setting indicators and countries
indicator_code = 'SP.POP.TOTL'
country_abbr = 'sz;us'

# The url
url = f'http://api.worldbank.org/v2/countries/{country_abbr}/indicators/{indicator_code}/?format=json&per_page=1000'

# Start request
r = requests.get(url)

# Loading Json Data into Dataframe

In [44]:
pd.DataFrame(r.json()[1]).where(
    lambda x: x!='').assign(
    country=lambda x: x.country.apply(lambda x: x.get('value')),
    indicator=lambda x: x.indicator.apply(lambda x: x.get('value'))).drop(
    ['decimal'], axis=1).dropna(
    how='all', axis=1)

           country countryiso3code  date          indicator        value
0         Eswatini             SWZ  2018  Population, total          NaN
1         Eswatini             SWZ  2017  Population, total    1367254.0
2         Eswatini             SWZ  2016  Population, total    1343098.0
3         Eswatini             SWZ  2015  Population, total    1319011.0
4         Eswatini             SWZ  2014  Population, total    1295097.0
5         Eswatini             SWZ  2013  Population, total    1271456.0
6         Eswatini             SWZ  2012  Population, total    1248158.0
7         Eswatini             SWZ  2011  Population, total    1225258.0
8         Eswatini             SWZ  2010  Population, total    1202843.0
9         Eswatini             SWZ  2009  Population, total    1180675.0
10        Eswatini             SWZ  2008  Population, total    1158897.0
11        Eswatini             SWZ  2007  Population, total    1138434.0
12        Eswatini             SWZ  2006  Population, total    1120514.0
13        Eswatini             SWZ  2005  Population, total    1105873.0
14        Eswatini             SWZ  2004  Population, total    1095053.0
15        Eswatini             SWZ  2003  Population, total    1087392.0
16        Eswatini             SWZ  2002  Population, total    1080930.0
17        Eswatini             SWZ  2001  Population, total    1072927.0
18        Eswatini             SWZ  2000  Population, total    1061468.0
19        Eswatini             SWZ  1999  Population, total    1045629.0
20        Eswatini             SWZ  1998  Population, total    1026009.0
21        Eswatini             SWZ  1997  Population, total    1003995.0
22        Eswatini             SWZ  1996  Population, total     981764.0
23        Eswatini             SWZ  1995  Population, total     960792.0
24        Eswatini             SWZ  1994  Population, total     941774.0
25        Eswatini             SWZ  1993  Population, total     924025.0
26        Eswatini             SWZ  1992  Population, total     906034.0
27        Eswatini             SWZ  1991  Population, total     885623.0
28        Eswatini             SWZ  1990  Population, total     861373.0
29        Eswatini             SWZ  1989  Population, total     832682.0
..             ...             ...   ...                ...          ...
88   United States             USA  1989  Population, total  246819000.0
89   United States             USA  1988  Population, total  244499000.0
90   United States             USA  1987  Population, total  242289000.0
91   United States             USA  1986  Population, total  240133000.0
92   United States             USA  1985  Population, total  237924000.0
93   United States             USA  1984  Population, total  235825000.0
94   United States             USA  1983  Population, total  233792000.0
95   United States             USA  1982  Population, total  231664000.0
96   United States             USA  1981  Population, total  229466000.0
97   United States             USA  1980  Population, total  227225000.0
98   United States             USA  1979  Population, total  225055000.0
99   United States             USA  1978  Population, total  222585000.0
100  United States             USA  1977  Population, total  220239000.0
101  United States             USA  1976  Population, total  218035000.0
102  United States             USA  1975  Population, total  215973000.0
103  United States             USA  1974  Population, total  213854000.0
104  United States             USA  1973  Population, total  211909000.0
105  United States             USA  1972  Population, total  209896000.0
106  United States             USA  1971  Population, total  207661000.0
107  United States             USA  1970  Population, total  205052000.0
108  United States             USA  1969  Population, total  202677000.0
109  United States             USA  1968  Population, total  200706000.0
110  United States             USA  1967  Population, total  198712000.0
111  United States             USA  1966  Population, total  196560000.0
112  United States             USA  1965  Population, total  194303000.0
113  United States             USA  1964  Population, total  191889000.0
114  United States             USA  1963  Population, total  189242000.0
115  United States             USA  1962  Population, total  186538000.0
116  United States             USA  1961  Population, total  183691000.0
117  United States             USA  1960  Population, total  180671000.0

[118 rows x 5 columns]